service: http-api
frameworkVersion: "3"

provider: 
  name: aws
  runtime: nodejs18.x

function:
  hellofn:
    handler: hello.handler
    events:
      -httpApi:
        path: /hello
        method: GET
